version: '3.8'

services:
  dailies-bot:
    build: .
    container_name: dailies-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1